# Generated by Django 4.2 on 2024-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='cat',
        ),
        migrations.AddField(
            model_name='adoption',
            name='cats',
            field=models.ManyToManyField(to='cats.cats'),
        ),
    ]
