# Generated by Django 3.2.23 on 2023-12-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20231215_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('about_you', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
        migrations.AlterModelOptions(
            name='cats',
            options={},
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='image',
            new_name='featured_image',
        ),
        migrations.AlterField(
            model_name='cats',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='application',
            name='adopt_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.cats'),
        ),
    ]
