# Generated by Django 4.2 on 2024-03-18 14:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_remove_adoption_cat_adoption_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
