# Generated by Django 3.2.23 on 2023-12-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20231217_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='adopt_cat',
        ),
        migrations.RemoveField(
            model_name='cats',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='cats',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cats',
            name='catname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cats',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cats',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
