# Generated by Django 3.2.23 on 2023-12-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20231217_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cats',
            name='selected',
        ),
        migrations.AlterField(
            model_name='cats',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
