# Generated by Django 4.2 on 2024-03-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_adoption_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cats',
            name='born',
        ),
        migrations.AddField(
            model_name='cats',
            name='date_born',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
