# Generated by Django 3.2.23 on 2023-12-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_alter_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cats.cats'),
        ),
    ]
