# Generated by Django 3.2.23 on 2023-12-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_application_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
