# Generated by Django 3.2.23 on 2023-12-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_cats_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cats',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='cats',
            name='image',
            field=models.ImageField(blank=True, upload_to='mayas_cats/'),
        ),
    ]
