# Generated by Django 3.2.23 on 2023-12-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_auto_20231219_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cats',
            name='image',
        ),
        migrations.AddField(
            model_name='cats',
            name='featured_image',
            field=models.ImageField(default='mayas_cats/default-cat.png', upload_to='mayas_cats/'),
        ),
    ]
