# Generated by Django 3.2.23 on 2023-12-22 00:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0011_auto_20231219_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dhciyvwx5/image/upload/v1703025226/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
