# Generated by Django 4.2.8 on 2023-12-22 22:39

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0014_alter_cats_options_cats_author_alter_cats_catname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('date_of_birth', models.DateField()),
                ('about_you', models.TextField(help_text='Tell us about you')),
            ],
        ),
        migrations.AlterField(
            model_name='cats',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AddField(
            model_name='adoption',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cats.cats'),
        ),
    ]
