# Generated by Django 4.2.8 on 2023-12-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0017_alter_adoption_about_you_alter_adoption_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='cats',
            name='selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cats',
            name='status',
            field=models.IntegerField(choices=[('draft', 'draft'), ('published', 'published')], default=0),
        ),
    ]
