# Generated by Django 4.2.8 on 2023-12-24 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0018_remove_adoption_cat_id_cats_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cats',
            name='author',
        ),
        migrations.AddField(
            model_name='adoption',
            name='adopt_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cats.cats'),
        ),
    ]
