# Generated by Django 4.2.8 on 2023-12-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0019_remove_cats_author_adoption_adopt_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cats',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='adopt_cat',
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cats',
            name='catname',
        ),
        migrations.RemoveField(
            model_name='cats',
            name='selected',
        ),
        migrations.AddField(
            model_name='adoption',
            name='catname',
            field=models.ManyToManyField(to='cats.cats'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='adoption',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cats',
            name='adopt_status',
            field=models.CharField(choices=[('Not yet ready for adoption', 'Not yet ready for adoption'), ('Ready for adoption', 'Ready for adoption'), ('Booked', 'Booked'), ('Adopted', 'Adopted')], default='Ready for adoption'),
        ),
        migrations.AddField(
            model_name='cats',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cats',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='about_you',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cats',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft'),
        ),
    ]
