# Generated by Django 4.2.8 on 2023-12-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0020_alter_cats_options_remove_adoption_adopt_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
