# Generated by Django 4.2 on 2024-03-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0021_alter_cats_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='catname',
        ),
        migrations.AddField(
            model_name='adoption',
            name='catname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.cats'),
        ),
    ]
